### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by mikemhenry** [cmelab/notebook_tutorials#14]
with pytest + nbval we can ensure that our notebooks run without errors, which I think is especially important for tutorials since nothing is more demotivating that when someone says "here use this to learn" but the thing is broken

**Comment by jennyfothergill** [comment]
That would be awesome! I've never set up CI-- what is the first step?

**Comment by mikemhenry** [comment]
First step will be to figure out a CI provider, does github have a built in thing? I've used travis.io, shipable, azure, and circleci. Oh and gitlab's built in one. If github had a built in one we could use, then that would probably be the essayist to setup and fun to test for a simple repo like this.

**Comment by jennyfothergill** [comment]
github Actions is the built in guy

**Comment by mikemhenry** [comment]
Cool so we can use that then. To test the notebooks, we can use something like:
`python -m pytest -v --nbval --nbval-lax` which will run the notebooks and check to make sure they run without error. We can use `--ignore=` for the notebook that isn't working.

**Comment by jennyfothergill** [comment]
done!
