### ISSUE TITLE
Tutorial Ideas

### ISSUE THREAD

**Issue by chrisjonesBSU** [cmelab/notebook_tutorials#6]
We've talked about creating tutorials that focus on molecular dynamics related topics as opposed to going into detail about individual MosDef packages and their API (but making an effort to use them within the tutorials as examples of their applications).

It would be helpful to get some input on potential tutorial ideas.

Here is a start

- OPV Sim: System specific example, talks a bit about corase-graining
- Temperature and Tau: How to identify the effect of changing tau; too small, too big.
- RDFs: Seems like a logical next step with the new u-grad hires.
- MSDs 
- Decorrelation and independence sampling

Feel free to comment with any additional ideas.

**Comment by mikemhenry** [comment]
I would maybe add a quick intro to MD tutorial that starts with a LJ sim that shows how when you run the simulation for enough time it equilibrates which would give some more context for the "Decorrelation and independence sampling" notebook.

**Comment by jennyfothergill** [comment]
I like this idea! I'll start an intro MD one. I may move some of the LJ explanation from the RDF one there

**Comment by jennyfothergill** [comment]
Make a "What do I do for my first day on Fry?" and link with "how to set up environment/use notebooks on Fry"

**Comment by jennyfothergill** [comment]
A rhaco analysis notebook https://bitbucket.org/cmelab/rhaco/src/master/ or a signac notebook or working with large data spaces notebook would be great
- MSD, residence time, rdf, other things?

**Comment by mikemhenry** [comment]
Freud is missing a MSD example, so I'm sure they would love it if we contributed a tutorial back to them :)

**Comment by jennyfothergill** [comment]
@ramanishsingh requested a tutorial showing how to set up a high density system that may need a shrink step

**Comment by chrisjonesBSU** [comment]
Ok nice :) That is what planckton does currently, so we can use that to get started on creating an example.

**Comment by jennyfothergill** [comment]
let's close this issue an make individual issues for each idea c:
